import { neon } from '@neondatabase/serverless'

interface Env { DATABASE_URL?: string; TRUCKHUB_ADMIN_EMAIL?: string; TRUCKHUB_ADMIN_BOOTSTRAP_PASSWORD?: string }
const COOKIE='truckhub_admin_session'
const CSRF_COOKIE='truckhub_admin_csrf'
const enc=new TextEncoder()
const PBKDF2_ITERATIONS=210000
const LOCK_AFTER=5
const LOCK_MINUTES=15
const SESSION_HOURS=8
const ROTATE_AFTER_MINUTES=30

function bytesToB64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function b64ToBytes(value:string){const s=atob(value);const out=new Uint8Array(s.length);for(let i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out}
async function sha256(value:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(value));return bytesToB64(new Uint8Array(d))}
async function passwordHash(value:string){const salt=new Uint8Array(16);crypto.getRandomValues(salt);const key=await crypto.subtle.importKey('raw',enc.encode(value),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:PBKDF2_ITERATIONS,hash:'SHA-256'},key,256);return `pbkdf2$${PBKDF2_ITERATIONS}$${bytesToB64(salt)}$${bytesToB64(new Uint8Array(bits))}`}
async function verifyPassword(value:string,stored:string){if(stored.startsWith('pbkdf2$')){const parts=stored.split('$');if(parts.length!==4)return false;const iterations=Number(parts[1]);if(!Number.isInteger(iterations)||iterations<100000||iterations>1000000)return false;const salt=b64ToBytes(parts[2]),expected=b64ToBytes(parts[3]);const key=await crypto.subtle.importKey('raw',enc.encode(value),'PBKDF2',false,['deriveBits']);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},key,256));if(bits.length!==expected.length)return false;let diff=0;for(let i=0;i<bits.length;i++)diff|=bits[i]^expected[i];return diff===0}const legacy=await sha256(value);return equal(legacy,stored)}
function equal(a:string,b:string){const x=enc.encode(a),y=enc.encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return bytesToB64(bytes)}
function cookie(v:string){return `${COOKIE}=${encodeURIComponent(v)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${SESSION_HOURS*3600}`}
function csrfCookie(v:string){return `${CSRF_COOKIE}=${encodeURIComponent(v)}; Secure; SameSite=Strict; Path=/; Max-Age=${SESSION_HOURS*3600}`}
function readCookie(req:Request,name:string){const raw=req.headers.get('Cookie')??'';for(const part of raw.split(';')){const [k,...v]=part.trim().split('=');if(k===name){try{return decodeURIComponent(v.join('='))}catch{return v.join('=')}}}return null}
function json(c:any,data:any,status=200){return c.json(data,{status,headers:{'Cache-Control':'no-store'}})}
function bad(message:string,status=400){return new Response(JSON.stringify({ok:false,error:message}),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
function setSessionCookies(response:Response,raw:string,csrf:string){response.headers.append('Set-Cookie',cookie(raw));response.headers.append('Set-Cookie',csrfCookie(csrf))}
function clearSessionCookies(response:Response){response.headers.append('Set-Cookie',`${COOKIE}=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0`);response.headers.append('Set-Cookie',`${CSRF_COOKIE}=; Secure; SameSite=Strict; Path=/; Max-Age=0`)}

async function cleanupAdminSessions(sql:any){await sql`DELETE FROM admin_sessions WHERE id IN (SELECT id FROM admin_sessions WHERE (revoked_at IS NOT NULL AND revoked_at<NOW()-INTERVAL '1 day') OR (expires_at<NOW()-INTERVAL '1 day') ORDER BY expires_at ASC LIMIT 500)`}

async function admin(c:any){if(!c.env.DATABASE_URL)return null;const t=readCookie(c.req.raw,COOKIE);if(!t)return null;const sql=neon(c.env.DATABASE_URL),h=await sha256(t);const rows=await sql`SELECT a.id,a.email,s.id AS session_id,s.csrf_token_hash,s.created_at,s.expires_at,s.absolute_expires_at,s.rotated_at FROM admin_sessions s JOIN admin_users a ON a.id=s.admin_user_id WHERE s.token_hash=${h} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND a.status='active' AND (a.locked_until IS NULL OR a.locked_until<=NOW()) LIMIT 1`;if(!rows[0])return null;await sql`UPDATE admin_sessions SET last_seen_at=NOW() WHERE id=${rows[0].session_id}`;return rows[0]}
async function requireMutation(c:any){const u=await admin(c);if(!u)return null;const header=c.req.header('X-TruckHub-Admin-CSRF')??'';const raw=readCookie(c.req.raw,CSRF_COOKIE)??'';if(!header||!raw)return null;const expected=await sha256(raw);if(!u.csrf_token_hash||!equal(header,raw)||!equal(expected,u.csrf_token_hash))return null;return u}
async function rotateSession(c:any,u:any){if(!c.env.DATABASE_URL)return null;const sql=neon(c.env.DATABASE_URL);const oldExpiry=new Date(u.absolute_expires_at??u.expires_at).getTime();const now=Date.now();if(oldExpiry<=now)return null;const lastRotation=u.rotated_at?new Date(u.rotated_at).getTime():new Date(u.created_at).getTime();if(now-lastRotation<ROTATE_AFTER_MINUTES*60*1000)return null;const raw=randomToken(),csrf=randomToken(),h=await sha256(raw),csrfHash=await sha256(csrf);const rows=await sql`UPDATE admin_sessions SET revoked_at=NOW(),rotated_at=NOW() WHERE id=${u.session_id} AND revoked_at IS NULL AND expires_at>NOW() RETURNING id`;if(!rows[0])return null;await sql`INSERT INTO admin_sessions(admin_user_id,token_hash,csrf_token_hash,expires_at,absolute_expires_at,rotated_at,last_seen_at) VALUES(${u.id},${h},${csrfHash},to_timestamp(${oldExpiry}/1000.0),to_timestamp(${oldExpiry}/1000.0),NOW(),NOW())`;return {raw,csrf}}
async function audit(sql:any,userId:string|null,action:string,targetType:string|null,targetId:string|null,detail:any=null){await sql`INSERT INTO admin_audit_logs(admin_user_id,action,target_type,target_id,detail) VALUES(${userId},${action},${targetType},${targetId},${detail})`}

export function registerAdminCenterRoutes(app:any){
  app.post('/admin/auth/login',async c=>{if(!c.env.DATABASE_URL)return bad('Banco não configurado.',503);const sql=neon(c.env.DATABASE_URL);await cleanupAdminSessions(sql);const data=await c.req.json().catch(()=>null) as any;if(!data?.email||!data?.password)return bad('Credenciais inválidas.',400);const email=String(data.email).trim().toLowerCase(),password=String(data.password);let rows=await sql`SELECT id,status,password_hash,failed_login_count,locked_until FROM admin_users WHERE email=${email} LIMIT 1`;let id=rows[0]?.id;let verified=false;if(!rows[0]){const bootstrapEmail=String(c.env.TRUCKHUB_ADMIN_EMAIL??'').trim().toLowerCase(),bootstrapPassword=String(c.env.TRUCKHUB_ADMIN_BOOTSTRAP_PASSWORD??'');if(!bootstrapEmail||!bootstrapPassword||email!==bootstrapEmail||!equal(password,bootstrapPassword))return bad('Credenciais inválidas.',401);const created=await sql`INSERT INTO admin_users(email,password_hash) VALUES(${email},${await passwordHash(password)}) RETURNING id`;id=created[0].id;verified=true}else{if(rows[0].status!=='active')return bad('Admin bloqueado.',403);if(rows[0].locked_until&&new Date(rows[0].locked_until).getTime()>Date.now())return bad('Admin temporariamente bloqueado. Tente novamente mais tarde.',429);verified=await verifyPassword(password,String(rows[0].password_hash));if(!verified){const failures=Number(rows[0].failed_login_count||0)+1;if(failures>=LOCK_AFTER){await sql`UPDATE admin_users SET failed_login_count=0,locked_until=NOW()+make_interval(mins=>${LOCK_MINUTES}),updated_at=NOW() WHERE id=${rows[0].id}`;return bad('Muitas tentativas. Admin bloqueado temporariamente.',429)}await sql`UPDATE admin_users SET failed_login_count=${failures},updated_at=NOW() WHERE id=${rows[0].id}`;return bad('Credenciais inválidas.',401)}if(!String(rows[0].password_hash).startsWith('pbkdf2$'))await sql`UPDATE admin_users SET password_hash=${await passwordHash(password)},updated_at=NOW() WHERE id=${rows[0].id}`;await sql`UPDATE admin_users SET failed_login_count=0,locked_until=NULL WHERE id=${rows[0].id}`}if(!verified)return bad('Credenciais inválidas.',401);const raw=randomToken(),csrf=randomToken(),h=await sha256(raw),csrfHash=await sha256(csrf);await sql`UPDATE admin_sessions SET revoked_at=NOW() WHERE admin_user_id=${id} AND revoked_at IS NULL`;await sql`INSERT INTO admin_sessions(admin_user_id,token_hash,csrf_token_hash,expires_at,absolute_expires_at,rotated_at,last_seen_at) VALUES(${id},${h},${csrfHash},NOW()+make_interval(hours=>${SESSION_HOURS}),NOW()+make_interval(hours=>${SESSION_HOURS}),NOW(),NOW())`;await sql`UPDATE admin_users SET last_login_at=NOW(),updated_at=NOW() WHERE id=${id}`;await audit(sql,id,'admin_login',null,null,null);const response=json(c,{ok:true,admin:{id,email}});setSessionCookies(response,raw,csrf);return response})
  app.post('/admin/auth/refresh',async c=>{if(!c.env.DATABASE_URL)return bad('Banco não configurado.',503);const u=await requireMutation(c);if(!u)return bad('Sessão administrativa inválida.',401);const sql=neon(c.env.DATABASE_URL);await cleanupAdminSessions(sql);const rotated=await rotateSession(c,u);if(!rotated)return json(c,{ok:true,rotated:false});await audit(sql,u.id,'admin_session_rotated','admin_session',u.session_id,null);const response=json(c,{ok:true,rotated:true});setSessionCookies(response,rotated.raw,rotated.csrf);return response})
  app.post('/admin/auth/revoke-all',async c=>{if(!c.env.DATABASE_URL)return bad('Banco não configurado.',503);const u=await requireMutation(c);if(!u)return bad('Sessão administrativa inválida.',401);const sql=neon(c.env.DATABASE_URL);await audit(sql,u.id,'admin_sessions_revoked_all','admin_user',u.id,null);await sql`UPDATE admin_sessions SET revoked_at=NOW() WHERE admin_user_id=${u.id} AND revoked_at IS NULL`;const response=json(c,{ok:true,revoked:true});clearSessionCookies(response);return response})
  app.post('/admin/auth/logout',async c=>{if(!c.env.DATABASE_URL)return json(c,{ok:true});const u=await admin(c);const sql=neon(c.env.DATABASE_URL);await cleanupAdminSessions(sql);const raw=readCookie(c.req.raw,COOKIE);if(u)await audit(sql,u.id,'admin_logout',null,null,null);if(raw)await sql`UPDATE admin_sessions SET revoked_at=NOW() WHERE token_hash=${await sha256(raw)} AND revoked_at IS NULL`;const response=json(c,{ok:true});clearSessionCookies(response);return response})
  app.get('/admin/me',async c=>{if(c.env.DATABASE_URL)await cleanupAdminSessions(neon(c.env.DATABASE_URL));const u=await admin(c);if(!u)return bad('Sessão administrativa inválida.',401);const response=json(c,{ok:true,admin:{id:u.id,email:u.email}});const rotated=await rotateSession(c,u);if(rotated){setSessionCookies(response,rotated.raw,rotated.csrf);await audit(neon(c.env.DATABASE_URL),u.id,'admin_session_rotated','admin_session',u.session_id,null)}return response})
  app.get('/admin/dashboard',async c=>{const u=await admin(c);if(!u)return bad('Não autorizado.',401);const sql=neon(c.env.DATABASE_URL);const [users,licenses,trips,payments]=await Promise.all([sql`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='active')::int AS active,COUNT(*) FILTER(WHERE status='blocked')::int AS blocked FROM users`,sql`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='trial')::int AS trial,COUNT(*) FILTER(WHERE license_type='lifetime' AND status='active')::int AS lifetime,COUNT(*) FILTER(WHERE status='expired')::int AS expired FROM licenses`,sql`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='active')::int AS active,COUNT(*) FILTER(WHERE status='finished')::int AS finished FROM trips`,sql`SELECT COUNT(*) FILTER(WHERE status='approved')::int AS approved,COALESCE(SUM(amount) FILTER(WHERE status='approved'),0)::numeric AS revenue FROM payments WHERE provider='mercado_pago'`]);return json(c,{ok:true,users:users[0],licenses:licenses[0],trips:trips[0],payments:payments[0]})})
  app.get('/admin/users',async c=>{const u=await admin(c);if(!u)return bad('Não autorizado.',401);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT u.id,u.name,u.email,u.status,u.created_at,l.id AS license_id,l.license_type,l.status AS license_status,l.expires_at,d.status AS device_status FROM users u LEFT JOIN licenses l ON l.user_id=u.id LEFT JOIN devices d ON d.license_id=l.id ORDER BY u.created_at DESC LIMIT 200`;return json(c,{ok:true,users:rows})})
  app.post('/admin/users/:id/status',async c=>{const u=await requireMutation(c);if(!u)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const data=await c.req.json().catch(()=>null) as any;if(!['active','blocked'].includes(data?.status))return bad('Status inválido.');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE users SET status=${data.status},updated_at=NOW() WHERE id=${id} RETURNING id,status`;if(!rows[0])return bad('Usuário não encontrado.',404);await sql`UPDATE sessions SET revoked_at=NOW() WHERE user_id=${id} AND revoked_at IS NULL`;await audit(sql,u.id,`user_${data.status}`,'user',id,{status:data.status});return json(c,{ok:true,user:rows[0]})})
  app.post('/admin/licenses/:id/status',async c=>{const u=await requireMutation(c);if(!u)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const data=await c.req.json().catch(()=>null) as any;if(!['active','blocked','expired'].includes(data?.status))return bad('Status inválido.');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE licenses SET status=${data.status},updated_at=NOW() WHERE id=${id} RETURNING id,user_id,license_type,status,expires_at`;if(!rows[0])return bad('Licença não encontrada.',404);if(data.status==='blocked')await sql`UPDATE sessions SET revoked_at=NOW() WHERE user_id=${rows[0].user_id} AND session_type='desktop' AND revoked_at IS NULL`;await audit(sql,u.id,`license_${data.status}`,'license',id,{status:data.status});return json(c,{ok:true,license:rows[0]})})
  app.get('/admin/audit',async c=>{const u=await admin(c);if(!u)return bad('Não autorizado.',401);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT id,admin_user_id,action,target_type,target_id,detail,created_at FROM admin_audit_logs ORDER BY created_at DESC LIMIT 200`;return json(c,{ok:true,logs:rows})})
}
