import { neon } from '@neondatabase/serverless'
import { requireAdminMutation } from './adminCompleteSecurity'
function bad(message:string,status=400){return new Response(JSON.stringify({ok:false,error:message}),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));let s='';for(const b of new Uint8Array(d))s+=String.fromCharCode(b);return btoa(s)}
function token(req:Request){const raw=req.headers.get('Cookie')??'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k==='truckhub_admin_session'){try{return decodeURIComponent(v.join('='))}catch{return v.join('=')}}}return null}
async function admin(c:any){if(!c.env.DATABASE_URL)return null;const t=token(c.req.raw);if(!t)return null;const sql=neon(c.env.DATABASE_URL),h=await hash(t);const r=await sql`SELECT a.id,a.email FROM admin_sessions s JOIN admin_users a ON a.id=s.admin_user_id WHERE s.token_hash=${h} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND a.status='active' LIMIT 1`;return r[0]??null}
async function audit(sql:any,id:string,action:string,type:string|null,target:string|null,detail:any={}){await sql`INSERT INTO admin_audit_logs(admin_user_id,action,target_type,target_id,detail) VALUES(${id},${action},${type},${target},${detail})`}
export function registerAdminCompleteRoutes(app:any){
 app.get('/admin/payments',async c=>{const a=await admin(c);if(!a)return bad('Não autorizado.',401);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT p.id,p.user_id,u.name,u.email,p.provider,p.amount,p.currency,p.status,p.provider_status,p.status_detail,p.external_reference,p.external_id,p.preference_id,p.paid_at,p.created_at,p.updated_at FROM payments p JOIN users u ON u.id=p.user_id ORDER BY p.created_at DESC LIMIT 250`;return c.json({ok:true,payments:rows},{headers:{'Cache-Control':'no-store'}})})
 app.get('/admin/trips',async c=>{const a=await admin(c);if(!a)return bad('Não autorizado.',401);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT t.id,t.user_id,u.name,u.email,t.cargo,t.origin,t.destination,t.started_at,t.finished_at,t.distance_km,t.fuel_used_l,t.cargo_value_brl,t.status FROM trips t JOIN users u ON u.id=t.user_id ORDER BY t.started_at DESC LIMIT 250`;return c.json({ok:true,trips:rows},{headers:{'Cache-Control':'no-store'}})})
 app.get('/admin/devices',async c=>{const a=await admin(c);if(!a)return bad('Não autorizado.',401);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT d.id,d.device_id,d.status,d.activated_at,d.revoked_at,d.created_at,u.id AS user_id,u.name,u.email,l.id AS license_id,l.license_type,l.status AS license_status FROM devices d JOIN licenses l ON l.id=d.license_id JOIN users u ON u.id=l.user_id ORDER BY d.created_at DESC LIMIT 250`;return c.json({ok:true,devices:rows},{headers:{'Cache-Control':'no-store'}})})
 app.get('/admin/sessions',async c=>{const a=await admin(c);if(!a)return bad('Não autorizado.',401);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT s.id,s.user_id,u.name,u.email,s.session_type,s.device_id,s.created_at,s.last_seen_at,s.expires_at,s.revoked_at FROM sessions s JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC LIMIT 300`;return c.json({ok:true,sessions:rows},{headers:{'Cache-Control':'no-store'}})})
 app.post('/admin/users/:id/revoke-sessions',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE sessions SET revoked_at=NOW() WHERE user_id=${id} AND revoked_at IS NULL RETURNING id`;if(!rows.length)return bad('Nenhuma sessão ativa encontrada.',404);await audit(sql,a.id,'user_revoke_all_sessions','user',id,{count:rows.length});return c.json({ok:true,revoked:rows.length})})
 app.post('/admin/users/:id/delete',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE users SET status='deleted',updated_at=NOW() WHERE id=${id} AND status<>'deleted' RETURNING id,email`;if(!rows[0])return bad('Usuário não encontrado ou já excluído.',404);await sql`UPDATE sessions SET revoked_at=NOW() WHERE user_id=${id} AND revoked_at IS NULL`;await audit(sql,a.id,'user_soft_delete','user',id,{email:rows[0].email});return c.json({ok:true,user:rows[0]})})
 app.post('/admin/payments/:id/review',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const data=await c.req.json().catch(()=>null) as any;const status=String(data?.status??'');if(!['rejected','cancelled'].includes(status))return bad('Revisão manual só pode rejeitar ou cancelar. Pagamentos aprovados devem passar pelo Mercado Pago/webhook.',400);const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE payments SET status=${status},updated_at=NOW() WHERE id=${id} AND status IN ('pending','in_process') RETURNING id,user_id,status,amount,currency`;if(!rows[0])return bad('Pagamento não encontrado ou não pode ser revisado.',404);await audit(sql,a.id,'payment_manual_review','payment',id,{status});return c.json({ok:true,payment:rows[0]})})
}
