import { neon } from '@neondatabase/serverless'
import { requireAdminMutation } from './adminCompleteSecurity'
function bad(message:string,status=400){return new Response(JSON.stringify({ok:false,error:message}),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
async function hash(value:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));let s='';for(const b of new Uint8Array(d))s+=String.fromCharCode(b);return btoa(s)}
function cookieToken(req:Request){const raw=req.headers.get('Cookie')??'';for(const part of raw.split(';')){const [k,...v]=part.trim().split('=');if(k==='truckhub_admin_session'){try{return decodeURIComponent(v.join('='))}catch{return v.join('=')}}}return null}
async function admin(c:any){if(!c.env.DATABASE_URL)return null;const token=cookieToken(c.req.raw);if(!token)return null;const sql=neon(c.env.DATABASE_URL),h=await hash(token);const rows=await sql`SELECT a.id,a.email FROM admin_sessions s JOIN admin_users a ON a.id=s.admin_user_id WHERE s.token_hash=${h} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND a.status='active' LIMIT 1`;if(!rows[0])return null;await sql`UPDATE admin_sessions SET last_seen_at=NOW() WHERE token_hash=${h} AND revoked_at IS NULL`;return rows[0]}
async function audit(sql:any,adminId:string,action:string,type:string,id:string,detail:any={}){await sql`INSERT INTO admin_audit_logs(admin_user_id,action,target_type,target_id,detail) VALUES(${adminId},${action},${type},${id},${detail})`}
export function registerAdminManagementRoutes(app:any){
 app.get('/admin/users/:id',async c=>{const a=await admin(c);if(!a)return bad('Não autorizado.',401);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const [users,licenses,devices,sessions,trips]=await Promise.all([sql`SELECT id,name,email,status,created_at,updated_at FROM users WHERE id=${id} LIMIT 1`,sql`SELECT id,license_type,status,trial_started_at,trial_expires_at,activated_at,expires_at,created_at,updated_at FROM licenses WHERE user_id=${id} ORDER BY created_at DESC LIMIT 5`,sql`SELECT d.id,d.device_id,d.status,d.activated_at,d.revoked_at,d.created_at,l.id AS license_id FROM devices d JOIN licenses l ON l.id=d.license_id WHERE l.user_id=${id} ORDER BY d.created_at DESC`,sql`SELECT id,session_type,device_id,expires_at,revoked_at,created_at,last_seen_at FROM sessions WHERE user_id=${id} ORDER BY created_at DESC LIMIT 50`,sql`SELECT id,cargo,origin,destination,started_at,finished_at,distance_km,fuel_used_l,status,cargo_value_brl FROM trips WHERE user_id=${id} ORDER BY started_at DESC LIMIT 25`]);if(!users[0])return bad('Usuário não encontrado.',404);return c.json({ok:true,user:users[0],licenses,devices,sessions,trips},{headers:{'Cache-Control':'no-store'}})})
 app.post('/admin/devices/:id/revoke',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE devices d SET status='revoked',revoked_at=NOW() FROM licenses l WHERE d.id=${id} AND l.id=d.license_id RETURNING d.id,d.user_id,d.device_id,d.status,d.revoked_at`;if(!rows[0])return bad('Dispositivo não encontrado.',404);await sql`UPDATE sessions SET revoked_at=NOW() WHERE device_id=${id} AND session_type='desktop' AND revoked_at IS NULL`;await audit(sql,a.id,'device_revoke','device',id,{device_id:rows[0].device_id});return c.json({ok:true,device:rows[0]})})
 app.post('/admin/sessions/:id/revoke',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE sessions SET revoked_at=NOW() WHERE id=${id} AND revoked_at IS NULL RETURNING id,user_id,session_type,device_id,revoked_at`;if(!rows[0])return bad('Sessão não encontrada ou já revogada.',404);await audit(sql,a.id,'session_revoke','session',id,{session_type:rows[0].session_type,device_id:rows[0].device_id});return c.json({ok:true,session:rows[0]})})
 app.post('/admin/licenses/:id/lifetime',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE licenses SET license_type='lifetime',status='active',expires_at=NULL,activated_at=COALESCE(activated_at,NOW()),updated_at=NOW() WHERE id=${id} RETURNING id,user_id,license_type,status,expires_at`;if(!rows[0])return bad('Licença não encontrada.',404);await audit(sql,a.id,'license_grant_lifetime','license',id,{user_id:rows[0].user_id});return c.json({ok:true,license:rows[0]})})
 app.post('/admin/licenses/:id/revoke',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE licenses SET status='blocked',updated_at=NOW() WHERE id=${id} RETURNING id,user_id,license_type,status,expires_at`;if(!rows[0])return bad('Licença não encontrada.',404);await sql`UPDATE sessions SET revoked_at=NOW() WHERE user_id=${rows[0].user_id} AND session_type='desktop' AND revoked_at IS NULL`;await audit(sql,a.id,'license_revoke','license',id,{user_id:rows[0].user_id});return c.json({ok:true,license:rows[0]})})
 app.post('/admin/licenses/:id/trial',async c=>{const a=await requireAdminMutation(c);if(!a)return bad('Ação administrativa não autorizada.',403);const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const rows=await sql`UPDATE licenses SET license_type='trial',status='trial',trial_started_at=NOW(),trial_expires_at=NOW()+INTERVAL '7 days',expires_at=NOW()+INTERVAL '7 days',updated_at=NOW() WHERE id=${id} RETURNING id,user_id,license_type,status,trial_expires_at`;if(!rows[0])return bad('Licença não encontrada.',404);await sql`UPDATE sessions SET revoked_at=NOW() WHERE user_id=${rows[0].user_id} AND session_type='desktop' AND revoked_at IS NULL`;await audit(sql,a.id,'license_reset_trial','license',id,{user_id:rows[0].user_id});return c.json({ok:true,license:rows[0]})})
}
