import { neon } from '@neondatabase/serverless'
import { hashSessionToken, getCookie } from './sharedAuth'

const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
function round2(n:number){return Number(n.toFixed(2))}
function normalizeCargo(value:string|null){return(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function cargoKey(cargo:string|null){const s=normalizeCargo(cargo);if(/carvao|carvão/.test(s))return'carvao';if(/milho/.test(s))return'milho';if(/soja/.test(s))return'soja';if(/carro|veiculo|automovel/.test(s))return'veiculos';if(/pesad|maquina|equipamento|transformador/.test(s))return'pesada';if(/especial/.test(s))return'especial';return'default'}
function weightMultiplier(kg:number){const t=Math.max(0,kg)/1000;if(t<=20)return 1;if(t<=30)return 1.08;if(t<=40)return 1.18;return 1.30}
async function currentUser(c:any){if(!c.env.DATABASE_URL)return null;const bearer=c.req.header('Authorization')?.replace(/^Bearer\s+/i,'').trim();const token=bearer||getCookie(c.req.raw,'truckhub_session');if(!token)return null;const tokenHash=await hashSessionToken(token);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${tokenHash} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND u.status='active' LIMIT 1`;return rows[0]??null}
async function settings(sql:any){return(await sql`SELECT * FROM economy_settings WHERE id=TRUE LIMIT 1`)[0]??{fuel_price_brl:5.98,minimum_margin_pct:20,maintenance_pct_of_revenue:6,efficiency_bonus_pct:5,clean_delivery_bonus_pct:5}}
async function rates(sql:any,key:string){const r=await sql`SELECT rate_brl_km FROM cargo_rates WHERE cargo_key=${key} AND active=TRUE LIMIT 1`;if(r[0])return Number(r[0].rate_brl_km);const d=await sql`SELECT rate_brl_km FROM cargo_rates WHERE cargo_key='default' AND active=TRUE LIMIT 1`;return Number(d[0]?.rate_brl_km??2.8)}

export async function settleTripEconomy(sql:any,userId:string,tripId:string){
  const tripRows=await sql`SELECT id,cargo,cargo_mass_kg,distance_km,fuel_used_l,status FROM trips WHERE id=${tripId} AND user_id=${userId} LIMIT 1`;const trip=tripRows[0];if(!trip)return null
  const existing=await sql`SELECT id FROM economy_ledger WHERE trip_id=${tripId} AND entry_type='trip_income' LIMIT 1`;if(existing[0])return{alreadySettled:true}
  const s=await settings(sql);const distance=Math.max(0,Number(trip.distance_km)||0);const fuelLiters=Math.max(0,Number(trip.fuel_used_l)||0);const massKg=Math.max(0,Number(trip.cargo_mass_kg)||0);const key=cargoKey(trip.cargo);const rate=await rates(sql,key);const multiplier=weightMultiplier(massKg)
  const baseRevenue=distance*rate*multiplier;const fuelCost=round2(fuelLiters*Number(s.fuel_price_brl));const maintenanceEstimate=round2(baseRevenue*Number(s.maintenance_pct_of_revenue)/100);const minimumRevenue=round2((fuelCost+maintenanceEstimate)*(1+Number(s.minimum_margin_pct)/100));const protectedRevenue=Math.max(baseRevenue,minimumRevenue)
  const efficiencyBonus=fuelLiters>0&&distance>0&&fuelLiters/distance<=0.45?round2(protectedRevenue*Number(s.efficiency_bonus_pct)/100):0
  const cleanBonus=round2(protectedRevenue*Number(s.clean_delivery_bonus_pct)/100);const gross=round2(protectedRevenue+efficiencyBonus+cleanBonus)
  const fuelExisting=await sql`SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE user_id=${userId} AND trip_id=${tripId} AND type='fuel'`;let fuelExpense=Number(fuelExisting[0]?.total||0);if(fuelExpense<=0&&fuelCost>0){fuelExpense=fuelCost;await sql`INSERT INTO expenses(user_id,trip_id,type,description,amount) VALUES(${userId},${tripId},'fuel','Abastecimento calculado pela telemetria; preço configurado no TruckHub',${fuelExpense})`}
  const maintenanceExisting=await sql`SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE user_id=${userId} AND trip_id=${tripId} AND type='maintenance'`;let maintenanceExpense=Number(maintenanceExisting[0]?.total||0);if(maintenanceExpense<=0&&maintenanceEstimate>0){maintenanceExpense=maintenanceEstimate;await sql`INSERT INTO expenses(user_id,trip_id,type,description,amount) VALUES(${userId},${tripId},'maintenance','Manutenção operacional automática da viagem',${maintenanceExpense})`}
  const allExpenses=await sql`SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE user_id=${userId} AND trip_id=${tripId}`;const totalExpenses=round2(Number(allExpenses[0]?.total||0));const netBeforeLoan=round2(Math.max(0,gross-totalExpenses))
  await sql`INSERT INTO economy_accounts(user_id,balance_brl) VALUES(${userId},0) ON CONFLICT(user_id) DO NOTHING`;const account=await sql`SELECT balance_brl FROM economy_accounts WHERE user_id=${userId}`;let balance=round2(Number(account[0]?.balance_brl||0));const openingBalance=balance
  balance=round2(balance+gross);await sql`UPDATE economy_accounts SET balance_brl=${balance},updated_at=NOW() WHERE user_id=${userId}`;await sql`INSERT INTO economy_ledger(user_id,trip_id,entry_type,description,amount_brl,balance_after_brl,metadata) VALUES(${userId},${tripId},'trip_income','Receita bruta da viagem',${gross},${balance},${JSON.stringify({cargo:trip.cargo,distanceKm:distance,rateBrlKm:rate,weightKg:massKg,weightMultiplier:multiplier,baseRevenue:round2(baseRevenue),minimumSustainableRevenue:minimumRevenue,protectedRevenue:round2(protectedRevenue),efficiencyBonus,cleanDeliveryBonus:cleanBonus})})`
  if(totalExpenses>0){balance=round2(Math.max(0,balance-totalExpenses));await sql`UPDATE economy_accounts SET balance_brl=${balance},updated_at=NOW() WHERE user_id=${userId}`;await sql`INSERT INTO economy_ledger(user_id,trip_id,entry_type,description,amount_brl,balance_after_brl,metadata) VALUES(${userId},${tripId},'trip_expenses','Combustível, manutenção e demais despesas da viagem',${-totalExpenses},${balance},${JSON.stringify({fuelCost:fuelExpense,maintenanceCost:maintenanceExpense,totalExpenses})})`}
  const loanRows=await sql`SELECT id,remaining_brl,repayment_pct FROM economy_loans WHERE user_id=${userId} AND status='active' ORDER BY created_at ASC LIMIT 1`;const loan=loanRows[0];let loanPayment=0;if(loan){loanPayment=round2(Math.min(Number(loan.remaining_brl),netBeforeLoan*Number(loan.repayment_pct)/100,balance));if(loanPayment>0){balance=round2(balance-loanPayment);const remaining=round2(Number(loan.remaining_brl)-loanPayment);await sql`UPDATE economy_accounts SET balance_brl=${balance},updated_at=NOW() WHERE user_id=${userId}`;await sql`UPDATE economy_loans SET remaining_brl=${remaining},status=${remaining<=0?'paid':'active'},paid_at=${remaining<=0?new Date().toISOString():null} WHERE id=${loan.id}`;await sql`INSERT INTO economy_ledger(user_id,trip_id,entry_type,description,amount_brl,balance_after_brl,metadata) VALUES(${userId},${tripId},'loan_payment','Parcela automática do empréstimo',${-loanPayment},${balance},${JSON.stringify({loanId:loan.id,repaymentPct:Number(loan.repayment_pct)})})`}}
  return{alreadySettled:false,distanceKm:round2(distance),fuelLiters:round2(fuelLiters),fuelPriceBrl:Number(s.fuel_price_brl),fuelCost:round2(fuelExpense),rateBrlKm:rate,weightMultiplier:multiplier,baseRevenue:round2(baseRevenue),minimumSustainableRevenue:minimumRevenue,gross,maintenance:round2(maintenanceExpense),totalExpenses,efficiencyBonus,cleanDeliveryBonus:cleanBonus,loanPayment,netBrl:round2(gross-totalExpenses-loanPayment),balanceBrl:balance,openingBalance}
}

export function registerEconomyRoutes(app:any){
 app.get('/me/economy',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});try{const sql=neon(c.env.DATABASE_URL);const account=await sql`SELECT balance_brl FROM economy_accounts WHERE user_id=${user.id}`;const ledger=await sql`SELECT id,trip_id,entry_type,description,amount_brl,balance_after_brl,metadata,created_at FROM economy_ledger WHERE user_id=${user.id} ORDER BY created_at DESC LIMIT 80`;const loan=await sql`SELECT id,principal_brl,remaining_brl,repayment_pct,status,created_at,paid_at FROM economy_loans WHERE user_id=${user.id} AND status='active' LIMIT 1`;return c.json({ok:true,account:{balanceBrl:Number(account[0]?.balance_brl||0)},loan:loan[0]??null,ledger})}catch(e){console.error(e);return c.json({ok:false,error:'Erro ao carregar o banco.'},{status:500})}})
 app.get('/me/economy/rates',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});const sql=neon(c.env.DATABASE_URL);const s=await settings(sql);const rows=await sql`SELECT cargo_key,display_name,rate_brl_km,active FROM cargo_rates WHERE active=TRUE ORDER BY display_name`;return c.json({ok:true,settings:{fuelPriceBrl:Number(s.fuel_price_brl),minimumMarginPct:Number(s.minimum_margin_pct),maintenancePct:Number(s.maintenance_pct_of_revenue),efficiencyBonusPct:Number(s.efficiency_bonus_pct),cleanDeliveryBonusPct:Number(s.clean_delivery_bonus_pct)},rates:rows})})
 app.post('/me/economy/loan',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});const body=await c.req.json().catch(()=>null) as any;const principal=Number(body?.principalBrl);const pct=Number(body?.repaymentPct??20);if(![5000,10000].includes(principal))return c.json({ok:false,error:'Empréstimo inicial disponível em R$ 5.000 ou R$ 10.000.'},{status:400});if(!Number.isFinite(pct)||pct<10||pct>50)return c.json({ok:false,error:'A parcela deve ficar entre 10% e 50% da receita líquida.'},{status:400});const sql=neon(c.env.DATABASE_URL);const existing=await sql`SELECT id FROM economy_loans WHERE user_id=${user.id} AND status='active' LIMIT 1`;if(existing[0])return c.json({ok:false,error:'Você já possui um empréstimo ativo.'},{status:409});await sql`INSERT INTO economy_accounts(user_id,balance_brl) VALUES(${user.id},0) ON CONFLICT(user_id) DO NOTHING`;const account=await sql`SELECT balance_brl FROM economy_accounts WHERE user_id=${user.id}`;const balance=round2(Number(account[0]?.balance_brl||0)+principal);const loan=await sql`INSERT INTO economy_loans(user_id,principal_brl,remaining_brl,repayment_pct) VALUES(${user.id},${principal},${principal},${pct}) RETURNING id,principal_brl,remaining_brl,repayment_pct,status,created_at`;await sql`UPDATE economy_accounts SET balance_brl=${balance},updated_at=NOW() WHERE user_id=${user.id}`;await sql`INSERT INTO economy_ledger(user_id,entry_type,description,amount_brl,balance_after_brl,metadata) VALUES(${user.id},'loan_credit','Crédito de empréstimo inicial',${principal},${balance},${JSON.stringify({loanId:loan[0].id})})`;return c.json({ok:true,loan:loan[0],balanceBrl:balance},201)})
 app.get('/me/trips/:id/economy-preview',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});const id=c.req.param('id');if(!UUID_RE.test(id))return c.json({ok:false,error:'Viagem não encontrada.'},{status:404});const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT id,cargo,cargo_mass_kg,distance_km,fuel_used_l,status FROM trips WHERE id=${id} AND user_id=${user.id} LIMIT 1`;if(!rows[0])return c.json({ok:false,error:'Viagem não encontrada.'},{status:404});const t=rows[0],s=await settings(sql),rate=await rates(sql,cargoKey(t.cargo)),distance=Math.max(0,Number(t.distance_km)||0),fuel=Math.max(0,Number(t.fuel_used_l)||0),mass=Math.max(0,Number(t.cargo_mass_kg)||0),multiplier=weightMultiplier(mass),base=distance*rate*multiplier,fuelCost=fuel*Number(s.fuel_price_brl),maintenance=base*Number(s.maintenance_pct_of_revenue)/100,minRevenue=(fuelCost+maintenance)*(1+Number(s.minimum_margin_pct)/100);return c.json({ok:true,preview:{cargo:t.cargo,distanceKm:round2(distance),fuelLiters:round2(fuel),fuelPriceBrl:Number(s.fuel_price_brl),fuelCost:round2(fuelCost),rateBrlKm:rate,weightMultiplier:multiplier,baseRevenue:round2(base),minimumSustainableRevenue:round2(minRevenue),projectedRevenue:round2(Math.max(base,minRevenue)),maintenance:round2(maintenance),status:t.status}})})
}
