import { neon } from '@neondatabase/serverless'
import { hashSessionToken, getCookie } from './sharedAuth'

async function currentUser(c:any){if(!c.env.DATABASE_URL)return null;const bearer=c.req.header('Authorization')?.replace(/^Bearer\s+/i,'').trim();const token=bearer||getCookie(c.req.raw,'truckhub_session');if(!token)return null;const tokenHash=await hashSessionToken(token);const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${tokenHash} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND u.status='active' LIMIT 1`;return rows[0]??null}

export function registerGarageRoutes(app:any){
 app.get('/me/garage',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT g.id,g.truck_id,g.exclusive,g.skin_code,g.label,t.truck_name,t.brand,t.model,t.license_plate FROM garage_assignments g JOIN trucks t ON t.id=g.truck_id WHERE g.user_id=${user.id} ORDER BY g.created_at DESC`;return c.json({ok:true,garage:rows})})
 app.post('/me/garage',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});const body=await c.req.json().catch(()=>null) as any;const truckId=String(body?.truckId??'');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(truckId))return c.json({ok:false,error:'Caminhão inválido.'},{status:400});const sql=neon(c.env.DATABASE_URL);const truck=await sql`SELECT id FROM trucks WHERE id=${truckId} AND user_id=${user.id} LIMIT 1`;if(!truck[0])return c.json({ok:false,error:'O caminhão não pertence a este motorista.'},{status:404});const existing=await sql`SELECT id FROM garage_assignments WHERE truck_id=${truckId} LIMIT 1`;if(existing[0])return c.json({ok:false,error:'Este caminhão já está vinculado a um motorista.'},{status:409});const row=await sql`INSERT INTO garage_assignments(user_id,truck_id,exclusive,skin_code,label) VALUES(${user.id},${truckId},${body?.exclusive!==false},${body?.skinCode??null},${body?.label??null}) RETURNING id,truck_id,exclusive,skin_code,label`;return c.json({ok:true,assignment:row[0]},201)})
 app.delete('/me/garage/:id',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});const id=c.req.param('id');const sql=neon(c.env.DATABASE_URL);const row=await sql`DELETE FROM garage_assignments WHERE id=${id} AND user_id=${user.id} RETURNING id`;if(!row[0])return c.json({ok:false,error:'Vínculo não encontrado.'},{status:404});return c.json({ok:true})})
 app.get('/me/garage/authorize',async c=>{const user=await currentUser(c);if(!user)return c.json({ok:false,error:'Sessão inválida ou expirada.'},{status:401});const brand=(c.req.query('brand')??'').trim();const model=(c.req.query('model')??'').trim();const plate=(c.req.query('plate')??'').trim();const sql=neon(c.env.DATABASE_URL);const count=await sql`SELECT COUNT(*)::int AS count FROM garage_assignments WHERE user_id=${user.id} AND exclusive=TRUE`;if(Number(count[0]?.count||0)===0)return c.json({ok:true,configured:false,authorized:true});const rows=await sql`SELECT g.id,g.label,g.skin_code,t.truck_name,t.brand,t.model,t.license_plate FROM garage_assignments g JOIN trucks t ON t.id=g.truck_id WHERE g.user_id=${user.id} AND g.exclusive=TRUE AND LOWER(COALESCE(t.brand,''))=LOWER(${brand}) AND LOWER(COALESCE(t.model,''))=LOWER(${model}) AND LOWER(COALESCE(t.license_plate,''))=LOWER(${plate}) LIMIT 1`;return c.json({ok:true,configured:true,authorized:Boolean(rows[0]),assignment:rows[0]??null})})
}
