import { Hono } from 'hono'
import { neon } from '@neondatabase/serverless'
import { registerAuthRoutes } from './auth'
import { registerActivationRoutes } from './activation'
import { registerTripTelemetryRoutes } from './tripTelemetry'
import { registerFinancialAdminRoutes } from './financialAdmin'
import { registerAdminCenterRoutes } from './adminCenter'
import { registerAdminManagementRoutes } from './adminManagement'
import { registerAdminCompleteRoutes } from './adminCenterComplete'
import { registerExpenseRoutes } from './expenses'
import { registerDriverDashboardRoutes } from './driverDashboard'
import { registerTransPoliEventRoutes } from './transpoliEvents'
import { getDatabaseUrl } from './config'
import { isUuid, parseTripMetric, parseTripStart, parseTripText } from './tripValidation'

interface Env { DATABASE_URL?: string; RATE_LIMIT_PEPPER?: string; MERCADOPAGO_ACCESS_TOKEN?: string; MERCADOPAGO_WEBHOOK_SECRET?: string; TRUCKHUB_PUBLIC_URL?: string; TRUCKHUB_API_PUBLIC_URL?: string; TRUCKHUB_LIFETIME_PRICE_BRL?: string; TRUCKHUB_ADMIN_EMAIL?: string; TRUCKHUB_ADMIN_BOOTSTRAP_PASSWORD?: string; ENVIRONMENT?: string; WEB_ORIGIN?: string }
const app=new Hono<{Bindings:Env}>();const SESSION_COOKIE='truckhub_session'
function getCookie(request:Request,name:string){const header=request.headers.get('Cookie')??'';for(const part of header.split(';')){const [key,...value]=part.trim().split('=');if(key===name){const raw=value.join('=');try{return decodeURIComponent(raw)}catch{return raw}}}return null}
function jsonError(message:string,status:any=400){return new Response(JSON.stringify({ok:false,error:message}),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
async function hashSessionToken(token:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));let binary='';for(const byte of new Uint8Array(digest))binary+=String.fromCharCode(byte);return btoa(binary)}
async function requireUser(c:any){const databaseUrl=c.env.DATABASE_URL;if(!databaseUrl)return null;const token=getCookie(c.req.raw,SESSION_COOKIE);if(!token)return null;const sql=neon(databaseUrl),tokenHash=await hashSessionToken(token);const rows=await sql`SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${tokenHash} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND u.status='active' AND s.session_type='web' LIMIT 1`;return rows[0]??null}
function normalizedOrigin(value:string|null){return(value??'').trim().replace(/\/$/,'')}
function configuredWebOrigin(env:Env){return normalizedOrigin(env.WEB_ORIGIN??'')||'https://truckhubweb.felipe-pessoall2026.workers.dev'}
function isAllowedOrigin(origin:string|null,env:Env){const normalized=normalizedOrigin(origin);if(!normalized)return false;const allowed=configuredWebOrigin(env);return normalized===allowed||normalized==='https://truckhubweb.felipe-pessoall2026.workers.dev'||normalized==='https://truckhub.felipe-pessoall2026.workers.dev'||normalized==='https://app.truckhub.com.br'}
app.use('*',async(c,next)=>{const origin=c.req.header('Origin'),allowed=configuredWebOrigin(c.env),isAllowed=isAllowedOrigin(origin,c.env);if(c.req.method==='OPTIONS'){if(!isAllowed)return new Response(null,{status:403,headers:{'Cache-Control':'no-store','Vary':'Origin'}});return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':normalizedOrigin(origin),'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-TruckHub-Admin-CSRF','Access-Control-Max-Age':'600','Vary':'Origin'}})}await next();if(origin&&isAllowed){c.res.headers.set('Access-Control-Allow-Origin',normalizedOrigin(origin));c.res.headers.set('Access-Control-Allow-Credentials','true');c.res.headers.set('Vary','Origin')}else if(origin)c.res.headers.set('Vary','Origin')})
app.use('*',async(c,next)=>{await next();c.res.headers.set('X-Content-Type-Options','nosniff');c.res.headers.set('X-Frame-Options','DENY');c.res.headers.set('Referrer-Policy','strict-origin-when-cross-origin');c.res.headers.set('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=()');c.res.headers.set('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'; base-uri 'none'");c.res.headers.set('X-Robots-Tag','noindex, nofollow')})
app.get('/health',async c=>{try{const sql=neon(getDatabaseUrl(c.env));const rows=await sql`SELECT NOW() AS database_time`;return c.json({ok:true,service:'truckhub-api',environment:c.env.ENVIRONMENT??'unknown',database:'ok',databaseTime:rows[0]?.database_time??null,configuration:{database:true,mercadoPago:!!c.env.MERCADOPAGO_ACCESS_TOKEN&&!!c.env.MERCADOPAGO_WEBHOOK_SECRET,lifetimePrice:!!c.env.TRUCKHUB_LIFETIME_PRICE_BRL,webOrigin:!!c.env.WEB_ORIGIN}},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('health_database_error',error);return jsonError('Banco de dados indisponível.',503)}})
app.get('/me/trips',async c=>{try{const user=await requireUser(c);if(!user)return jsonError('Sessão inválida ou expirada.',401);const sql=neon(getDatabaseUrl(c.env));const rows=await sql`SELECT t.id,t.truck_id,t.cargo,t.origin,t.destination,t.started_at,t.finished_at,t.distance_km,t.fuel_used_l,t.status,t.cargo_value_brl,tr.truck_name,tr.brand,tr.model,tr.license_plate FROM trips t LEFT JOIN trucks tr ON tr.id=t.truck_id AND tr.user_id=t.user_id WHERE t.user_id=${user.id} ORDER BY t.started_at DESC LIMIT 100`;return c.json({ok:true,trips:rows},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('trips_list_error',error);return jsonError('Erro ao carregar viagens.',500)}})
app.post('/me/trips',async c=>{try{const user=await requireUser(c);if(!user)return jsonError('Sessão inválida ou expirada.',401);const data=await c.req.json().catch(()=>null) as any;if(!data)return jsonError('JSON inválido.',400);const cargo=parseTripText(data.cargo,200),origin=parseTripText(data.origin,150),destination=parseTripText(data.destination,150);if(data.cargo!=null&&cargo===null)return jsonError('Carga inválida.',400);if(data.origin!=null&&origin===null)return jsonError('Origem inválida.',400);if(data.destination!=null&&destination===null)return jsonError('Destino inválido.',400);const truckId=data.truckId??null;if(truckId!==null&&!isUuid(truckId))return jsonError('Caminhão inválido.',400);const startedAt=parseTripStart(data.startedAt);if(!startedAt)return jsonError('Data de início inválida.',400);const sql=neon(getDatabaseUrl(c.env));const rows=await sql`WITH checked_truck AS (SELECT id FROM trucks WHERE id=${truckId} AND user_id=${user.id} LIMIT 1), inserted AS (INSERT INTO trips(user_id,truck_id,cargo,origin,destination,started_at) SELECT ${user.id},${truckId},${cargo},${origin},${destination},${startedAt.toISOString()} WHERE ${truckId} IS NULL OR EXISTS(SELECT 1 FROM checked_truck) RETURNING id,truck_id,cargo,origin,destination,started_at,status) SELECT * FROM inserted`;if(!rows[0])return jsonError('Caminhão inválido ou viagem já ativa.',409);return c.json({ok:true,trip:rows[0]},201)}catch(error){const message=error instanceof Error?error.message:'';if(message.includes('uq_trips_one_active_per_user')||message.toLowerCase().includes('duplicate'))return jsonError('Já existe uma viagem ativa.',409);console.error('trip_create_error',error);return jsonError('Erro ao iniciar viagem.',500)}})
app.post('/me/trips/:id/finish',async c=>{try{const user=await requireUser(c);if(!user)return jsonError('Sessão inválida ou expirada.',401);const id=c.req.param('id');if(!isUuid(id))return jsonError('Viagem não encontrada.',404);const data=await c.req.json().catch(()=>({})) as any;const distance=data.distanceKm==null?null:parseTripMetric(data.distanceKm,0,10000000);const fuel=data.fuelUsedL==null?null:parseTripMetric(data.fuelUsedL,0,2000);if(data.distanceKm!=null&&distance===null)return jsonError('Distância inválida.',400);if(data.fuelUsedL!=null&&fuel===null)return jsonError('Combustível inválido.',400);const sql=neon(getDatabaseUrl(c.env));const telemetry=await sql`SELECT COUNT(*)::int AS count,MIN(odometer_km) AS start_odometer,MAX(odometer_km) AS end_odometer,MIN(fuel_l) AS start_fuel,MAX(fuel_l) AS max_fuel FROM trip_telemetry_samples WHERE trip_id=${id}`;const sample=telemetry[0];let serverDistance=distance,serverFuel=fuel;if(Number(sample?.count||0)>0){const start=Number(sample.start_odometer),end=Number(sample.end_odometer);const minFuel=Number(sample.start_fuel);const maxFuel=Number(sample.max_fuel);if(Number.isFinite(start)&&Number.isFinite(end))serverDistance=Math.max(0,end-start);if(Number.isFinite(minFuel)&&Number.isFinite(maxFuel))serverFuel=Math.max(0,maxFuel-minFuel)}const rows=await sql`UPDATE trips SET finished_at=NOW(),distance_km=${serverDistance},fuel_used_l=${serverFuel},status='finished' WHERE id=${id} AND user_id=${user.id} AND status='active' RETURNING id,finished_at,distance_km,fuel_used_l,status,cargo_value_brl`;if(!rows[0])return jsonError('Viagem ativa não encontrada.',404);await sql`UPDATE tachographs SET updated_at=NOW() WHERE trip_id=${id}`;return c.json({ok:true,trip:rows[0]},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('trip_finish_error',error);return jsonError('Erro ao finalizar viagem.',500)}})
app.get('/me/trips/:tripId/summary',async c=>{try{const user=await requireUser(c);if(!user)return jsonError('Sessão inválida ou expirada.',401);const id=c.req.param('tripId');if(!isUuid(id))return jsonError('Viagem não encontrada.',404);const sql=neon(getDatabaseUrl(c.env));const rows=await sql`SELECT id,cargo,origin,destination,started_at,finished_at,distance_km,fuel_used_l,cargo_value_brl,status FROM trips WHERE id=${id} AND user_id=${user.id} LIMIT 1`;if(!rows[0])return jsonError('Viagem não encontrada.',404);const expenses=await sql`SELECT COALESCE(SUM(amount),0) AS total FROM expenses WHERE trip_id=${id} AND user_id=${user.id}`;const expenseTotal=Number(expenses[0]?.total||0);const cargoValue=rows[0].cargo_value_brl==null?null:Number(rows[0].cargo_value_brl);return c.json({ok:true,summary:{...rows[0],expensesBrl:Number(expenseTotal.toFixed(2)),resultBrl:cargoValue==null?null:Number((cargoValue-expenseTotal).toFixed(2))}},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('trip_summary_error',error);return jsonError('Erro ao carregar o resumo da viagem.',500)}})
registerAuthRoutes(app);registerActivationRoutes(app);registerTripTelemetryRoutes(app);registerFinancialAdminRoutes(app);registerAdminCenterRoutes(app);registerAdminManagementRoutes(app);registerAdminCompleteRoutes(app);registerExpenseRoutes(app);registerDriverDashboardRoutes(app);registerTransPoliEventRoutes(app)
app.notFound(c=>jsonError('Rota não encontrada.',404));export default app
