import { Hono } from 'hono'
import { neon } from '@neondatabase/serverless'
import { registerAuthRoutes } from './auth'
import { registerActivationRoutes } from './activation'
import { registerTripTelemetryRoutes } from './tripTelemetry'
import { registerEconomyRoutes, settleTripEconomy } from './economy'
import { registerGarageRoutes } from './garage'
import { registerGaragePhaseFRoutes } from './garagePhaseF'
import { registerFinancialAdminRoutes } from './financialAdmin'
import { registerAdminCenterRoutes } from './adminCenter'
import { registerAdminManagementRoutes } from './adminManagement'
import { registerAdminCompleteRoutes } from './adminCenterComplete'
import { registerExpenseRoutes } from './expenses'
import { registerDriverDashboardRoutes } from './driverDashboard'
import { registerTransPoliEventRoutes } from './transpoliEvents'
import { registerCargoMarketRoutes } from './cargoMarket'
import { registerNotesRoutes } from './notes'
import { getDatabaseUrl } from './config'
import { isUuid, parseTripMetric, parseTripStart, parseTripText } from './tripValidation'

interface Env { DATABASE_URL?: string; RATE_LIMIT_PEPPER?: string; MERCADOPAGO_ACCESS_TOKEN?: string; MERCADOPAGO_WEBHOOK_SECRET?: string; TRUCKHUB_PUBLIC_URL?: string; TRUCKHUB_API_PUBLIC_URL?: string; TRUCKHUB_LIFETIME_PRICE_BRL?: string; TRUCKHUB_ADMIN_EMAIL?: string; TRUCKHUB_ADMIN_BOOTSTRAP_PASSWORD?: string; ENVIRONMENT?: string; WEB_ORIGIN?: string }
