import { neon } from '@neondatabase/serverless'

const SESSION_COOKIE='truckhub_session'
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{12}$/i
const enc=new TextEncoder()
async function hash(value:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(value));let b='';for(const x of new Uint8Array(d))b+=String.fromCharCode(x);return btoa(b)}
function cookie(req:Request){const raw=req.headers.get('Cookie')??'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k===SESSION_COOKIE){try{return decodeURIComponent(v.join('='))}catch{return v.join('=')}}}return null}
async function currentUser(c:any){if(!c.env.DATABASE_URL)return null;const token=cookie(c.req.raw);if(!token)return null;const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${await hash(token)} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND s.session_type='web' AND u.status='active' LIMIT 1`;return rows[0]??null}
function err(message:string,status:number){return new Response(JSON.stringify({ok:false,error:message}),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
function text(v:any,max:number){const s=String(v??'').trim();return s?s.slice(0,max):null}

export function registerNotesRoutes(app:any){
  app.get('/me/notes',async c=>{try{const u=await currentUser(c);if(!u)return err('Sessão inválida ou expirada.',401);const q=c.req.query();const limit=Math.min(100,Math.max(1,Number.parseInt(q.limit??'50',10)||50));const sql=neon(c.env.DATABASE_URL!);const notes=await sql`SELECT id,title,content,created_at,updated_at FROM driver_notes WHERE user_id=${u.id} ORDER BY updated_at DESC LIMIT ${limit}`;return c.json({ok:true,notes},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error('notes_list_error',e);return err('Erro ao carregar notas.',500)}})
  app.post('/me/notes',async c=>{try{const u=await currentUser(c);if(!u)return err('Sessão inválida ou expirada.',401);const d=await c.req.json().catch(()=>null) as any;if(!d)return err('JSON inválido.',400);const title=text(d.title,120)??'Nota';const content=text(d.content,10000);if(!content)return err('O conteúdo da nota é obrigatório.',400);const sql=neon(c.env.DATABASE_URL!);const rows=await sql`INSERT INTO driver_notes(user_id,title,content) VALUES(${u.id},${title},${content}) RETURNING id,title,content,created_at,updated_at`;return c.json({ok:true,note:rows[0]},201)}catch(e){console.error('notes_create_error',e);return err('Erro ao salvar nota.',500)}})
  app.put('/me/notes/:id',async c=>{try{const u=await currentUser(c);if(!u)return err('Sessão inválida ou expirada.',401);const id=c.req.param('id');if(!UUID_RE.test(id))return err('Nota não encontrada.',404);const d=await c.req.json().catch(()=>null) as any;if(!d)return err('JSON inválido.',400);const title=text(d.title,120)??'Nota';const content=text(d.content,10000);if(!content)return err('O conteúdo da nota é obrigatório.',400);const sql=neon(c.env.DATABASE_URL!);const rows=await sql`UPDATE driver_notes SET title=${title},content=${content},updated_at=NOW() WHERE id=${id} AND user_id=${u.id} RETURNING id,title,content,created_at,updated_at`;if(!rows[0])return err('Nota não encontrada.',404);return c.json({ok:true,note:rows[0]})}catch(e){console.error('notes_update_error',e);return err('Erro ao atualizar nota.',500)}})
  app.delete('/me/notes/:id',async c=>{try{const u=await currentUser(c);if(!u)return err('Sessão inválida ou expirada.',401);const id=c.req.param('id');if(!UUID_RE.test(id))return err('Nota não encontrada.',404);const sql=neon(c.env.DATABASE_URL!);const rows=await sql`DELETE FROM driver_notes WHERE id=${id} AND user_id=${u.id} RETURNING id`;if(!rows[0])return err('Nota não encontrada.',404);return c.json({ok:true})}catch(e){console.error('notes_delete_error',e);return err('Erro ao excluir nota.',500)}})
}
