import { neon } from '@neondatabase/serverless'

const SESSION_COOKIE='truckhub_session'
const enc=new TextEncoder()
async function hash(value:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(value));let b='';for(const x of new Uint8Array(d))b+=String.fromCharCode(x);return btoa(b)}
function token(req:Request){const raw=req.headers.get('Cookie')??'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k===SESSION_COOKIE){try{return decodeURIComponent(v.join('='))}catch{return v.join('=')}}}const auth=req.headers.get('Authorization')??'';return auth.replace(/^Bearer\s+/i,'').trim()||null}
async function currentUser(c:any){if(!c.env.DATABASE_URL)return null;const t=token(c.req.raw);if(!t)return null;const sql=neon(c.env.DATABASE_URL);const rows=await sql`SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${await hash(t)} AND s.revoked_at IS NULL AND s.expires_at>NOW() AND s.session_type IN ('web','desktop') AND u.status='active' LIMIT 1`;return rows[0]??null}
function err(message:string,status:number){return new Response(JSON.stringify({ok:false,error:message}),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
function periodStart(period:string){if(period==='all')return null;const now=new Date();if(period==='today'){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const y=Number(parts.find(x=>x.type==='year')?.value),m=Number(parts.find(x=>x.type==='month')?.value),d=Number(parts.find(x=>x.type==='day')?.value);return new Date(Date.UTC(y,m-1,d,3,0,0));}const days=period==='7d'?7:30;return new Date(now.getTime()-days*86400000)}
function n(v:any,d=2){return Number(Number(v||0).toFixed(d))}

export function registerStatisticsRoutes(app:any){
 app.get('/me/statistics',async c=>{try{
  const u=await currentUser(c);if(!u)return err('Sessão inválida ou expirada.',401)
  const period=(c.req.query('period')||'all').toLowerCase();if(!['today','7d','30d','all'].includes(period))return err('Período inválido.',400)
  const sql=neon(c.env.DATABASE_URL!),from=periodStart(period)
  const trips=from===null?await sql`SELECT COUNT(*)::int trips,COALESCE(SUM(distance_km),0) distance_km,COALESCE(SUM(cargo_mass_kg),0) cargo_kg,COALESCE(SUM(fuel_used_l),0) fuel_l,COALESCE(SUM(cargo_value_brl),0) revenue_brl,COUNT(*) FILTER(WHERE cargo_damage=0)::int clean_deliveries,COUNT(*) FILTER(WHERE cargo_damage>0)::int damaged_deliveries,AVG(distance_km) avg_distance FROM trips WHERE user_id=${u.id} AND status='finished'`:await sql`SELECT COUNT(*)::int trips,COALESCE(SUM(distance_km),0) distance_km,COALESCE(SUM(cargo_mass_kg),0) cargo_kg,COALESCE(SUM(fuel_used_l),0) fuel_l,COALESCE(SUM(cargo_value_brl),0) revenue_brl,COUNT(*) FILTER(WHERE cargo_damage=0)::int clean_deliveries,COUNT(*) FILTER(WHERE cargo_damage>0)::int damaged_deliveries,AVG(distance_km) avg_distance FROM trips WHERE user_id=${u.id} AND status='finished' AND finished_at>=${from}`
  const expenses=from===null?await sql`SELECT COALESCE(SUM(amount),0) total_brl,COALESCE(SUM(amount) FILTER(WHERE type='fuel'),0) fuel_brl,COALESCE(SUM(amount) FILTER(WHERE type='maintenance'),0) maintenance_brl,COALESCE(SUM(amount) FILTER(WHERE type='toll'),0) toll_brl FROM expenses WHERE user_id=${u.id}`:await sql`SELECT COALESCE(SUM(amount),0) total_brl,COALESCE(SUM(amount) FILTER(WHERE type='fuel'),0) fuel_brl,COALESCE(SUM(amount) FILTER(WHERE type='maintenance'),0) maintenance_brl,COALESCE(SUM(amount) FILTER(WHERE type='toll'),0) toll_brl FROM expenses WHERE user_id=${u.id} AND created_at>=${from}`
  const cargo=from===null?await sql`SELECT COALESCE(NULLIF(TRIM(cargo),''),'Não informado') cargo,COUNT(*)::int trips,COALESCE(SUM(cargo_mass_kg),0) cargo_kg,COALESCE(SUM(distance_km),0) distance_km,COALESCE(SUM(cargo_value_brl),0) revenue_brl FROM trips WHERE user_id=${u.id} AND status='finished' GROUP BY 1 ORDER BY trips DESC,cargo`:await sql`SELECT COALESCE(NULLIF(TRIM(cargo),''),'Não informado') cargo,COUNT(*)::int trips,COALESCE(SUM(cargo_mass_kg),0) cargo_kg,COALESCE(SUM(distance_km),0) distance_km,COALESCE(SUM(cargo_value_brl),0) revenue_brl FROM trips WHERE user_id=${u.id} AND status='finished' AND finished_at>=${from} GROUP BY 1 ORDER BY trips DESC,cargo`
  const incidents=from===null?await sql`SELECT COUNT(DISTINCT e.trip_id)::int trips FROM transpoli_operational_events e JOIN trips t ON t.id=e.trip_id WHERE e.user_id=${u.id} AND t.status='finished' AND e.event_type ~* '(incident|damage|collision|crash|overspeed|speeding|hard.?brak|hard.?accel)'`:await sql`SELECT COUNT(DISTINCT e.trip_id)::int trips FROM transpoli_operational_events e JOIN trips t ON t.id=e.trip_id WHERE e.user_id=${u.id} AND t.status='finished' AND e.occurred_at>=${from} AND e.event_type ~* '(incident|damage|collision|crash|overspeed|speeding|hard.?brak|hard.?accel)'`
  const penalties=from===null?await sql`SELECT COALESCE(SUM(CASE WHEN metadata->>'damagePenalty' ~ '^[0-9]+(\\.[0-9]+)?$' THEN (metadata->>'damagePenalty')::numeric ELSE 0 END),0) total_brl FROM economy_ledger WHERE user_id=${u.id} AND entry_type='trip_income'`:await sql`SELECT COALESCE(SUM(CASE WHEN metadata->>'damagePenalty' ~ '^[0-9]+(\\.[0-9]+)?$' THEN (metadata->>'damagePenalty')::numeric ELSE 0 END),0) total_brl FROM economy_ledger WHERE user_id=${u.id} AND entry_type='trip_income' AND created_at>=${from}`
  const row=trips[0]??{},distance=Number(row.distance_km||0),fuel=Number(row.fuel_l||0),revenue=Number(row.revenue_brl||0),expenseTotal=Number(expenses[0]?.total_brl||0),tripCount=Number(row.trips||0),damaged=Number(row.damaged_deliveries||0),clean=Number(row.clean_deliveries||0),incidentTrips=Number(incidents[0]?.trips||0),costPerKm=distance>0?expenseTotal/distance:null
  const payload={period,trips:tripCount,completedTrips:tripCount,incidentTrips,nonIncidentTrips:Math.max(0,tripCount-incidentTrips),cleanDeliveries:clean,damagedDeliveries:damaged,damagePercent:tripCount>0?damaged/tripCount*100:null,damagePenaltiesBrl:n(penalties[0]?.total_brl),distanceKm:n(distance,1),averageDistanceKm:tripCount>0?Number(Number(row.avg_distance||0).toFixed(1)):null,cargoKg:n(row.cargo_kg,1),cargoTons:n(Number(row.cargo_kg||0)/1000,2),cargoTypes:cargo.length,fuelLiters:n(fuel,1),averageKmPerLiter:fuel>0?n(distance/fuel):null,averageFuelL100:distance>0?n(fuel/distance*100):null,revenueBrl:n(revenue),expensesBrl:n(expenseTotal),fuelExpensesBrl:n(expenses[0]?.fuel_brl),maintenanceBrl:n(expenses[0]?.maintenance_brl),tollBrl:n(expenses[0]?.toll_brl),profitBrl:n(revenue-expenseTotal),revenuePerKm:distance>0?n(revenue/distance):null,costPerKm:costPerKm===null?null:n(costPerKm),profitPerKm:distance>0?n((revenue-expenseTotal)/distance):null,profitPerTrip:tripCount>0?n((revenue-expenseTotal)/tripCount):null}
  const cargoRows=cargo.map((x:any)=>({cargo:String(x.cargo),trips:Number(x.trips||0),cargoKg:n(x.cargo_kg,1),distanceKm:n(x.distance_km,1),revenueBrl:n(x.revenue_brl)}))
  return c.json({ok:true,statistics:payload,byCargo:cargoRows},{headers:{'Cache-Control':'no-store'}})
 }catch(e){console.error('statistics_error',e);return err('Erro ao carregar estatísticas.',500)}})
}
