-- TruckHub V1 — estado de telemetria ao vivo por dispositivo.
-- Mantém somente a última leitura para o dashboard, sem transformar o banco em um log de 100 ms.
CREATE TABLE IF NOT EXISTS device_telemetry_latest (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  device_id VARCHAR(255) NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  connected BOOLEAN NOT NULL DEFAULT TRUE,
  game VARCHAR(20),
  game_paused BOOLEAN NOT NULL DEFAULT FALSE,
  engine_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  electric_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  speed_kph NUMERIC(8,2) NOT NULL DEFAULT 0,
  speed_limit_kph NUMERIC(8,2) NOT NULL DEFAULT 0,
  rpm NUMERIC(8,2) NOT NULL DEFAULT 0,
  gear INTEGER NOT NULL DEFAULT 0,
  fuel_l NUMERIC(12,2) NOT NULL DEFAULT 0,
  fuel_range_km NUMERIC(12,2) NOT NULL DEFAULT 0,
  fuel_avg_consumption NUMERIC(12,4) NOT NULL DEFAULT 0,
  adblue_l NUMERIC(12,2) NOT NULL DEFAULT 0,
  oil_pressure NUMERIC(12,2) NOT NULL DEFAULT 0,
  oil_temperature NUMERIC(12,2) NOT NULL DEFAULT 0,
  water_temperature NUMERIC(12,2) NOT NULL DEFAULT 0,
  battery_voltage NUMERIC(12,2) NOT NULL DEFAULT 0,
  odometer_km NUMERIC(12,2) NOT NULL DEFAULT 0,
  air_pressure NUMERIC(12,2) NOT NULL DEFAULT 0,
  brake_temperature NUMERIC(12,2) NOT NULL DEFAULT 0,
  parking_brake BOOLEAN NOT NULL DEFAULT FALSE,
  motor_brake BOOLEAN NOT NULL DEFAULT FALSE,
  brake_light BOOLEAN NOT NULL DEFAULT FALSE,
  cruise_control BOOLEAN NOT NULL DEFAULT FALSE,
  cruise_speed_kph NUMERIC(8,2) NOT NULL DEFAULT 0,
  retarder_level INTEGER NOT NULL DEFAULT 0,
  user_throttle NUMERIC(6,4) NOT NULL DEFAULT 0,
  effective_throttle NUMERIC(6,4) NOT NULL DEFAULT 0,
  user_brake NUMERIC(6,4) NOT NULL DEFAULT 0,
  effective_brake NUMERIC(6,4) NOT NULL DEFAULT 0,
  wear_engine NUMERIC(6,4) NOT NULL DEFAULT 0,
  wear_transmission NUMERIC(6,4) NOT NULL DEFAULT 0,
  wear_cabin NUMERIC(6,4) NOT NULL DEFAULT 0,
  wear_chassis NUMERIC(6,4) NOT NULL DEFAULT 0,
  wear_wheels NUMERIC(6,4) NOT NULL DEFAULT 0,
  cargo_damage NUMERIC(6,4) NOT NULL DEFAULT 0,
  air_pressure_warning BOOLEAN NOT NULL DEFAULT FALSE,
  air_pressure_emergency BOOLEAN NOT NULL DEFAULT FALSE,
  fuel_warning BOOLEAN NOT NULL DEFAULT FALSE,
  adblue_warning BOOLEAN NOT NULL DEFAULT FALSE,
  oil_pressure_warning BOOLEAN NOT NULL DEFAULT FALSE,
  water_temperature_warning BOOLEAN NOT NULL DEFAULT FALSE,
  battery_voltage_warning BOOLEAN NOT NULL DEFAULT FALSE,
  wipers BOOLEAN NOT NULL DEFAULT FALSE,
  blinker_left_active BOOLEAN NOT NULL DEFAULT FALSE,
  blinker_right_active BOOLEAN NOT NULL DEFAULT FALSE,
  lights_parking BOOLEAN NOT NULL DEFAULT FALSE,
  lights_brake BOOLEAN NOT NULL DEFAULT FALSE,
  lights_reverse BOOLEAN NOT NULL DEFAULT FALSE,
  lights_hazard BOOLEAN NOT NULL DEFAULT FALSE,
  differential_lock BOOLEAN NOT NULL DEFAULT FALSE,
  lift_axle BOOLEAN NOT NULL DEFAULT FALSE,
  trailer_lift_axle BOOLEAN NOT NULL DEFAULT FALSE,
  truck_brand VARCHAR(100),
  truck_model VARCHAR(120),
  license_plate VARCHAR(32),
  cargo VARCHAR(180),
  cargo_mass_kg NUMERIC(12,2) NOT NULL DEFAULT 0,
  source_city VARCHAR(180),
  destination_city VARCHAR(180),
  source_company VARCHAR(180),
  destination_company VARCHAR(180),
  planned_distance_km NUMERIC(12,2) NOT NULL DEFAULT 0,
  cargo_value_brl NUMERIC(14,2),
  on_job BOOLEAN NOT NULL DEFAULT FALSE,
  special_job BOOLEAN NOT NULL DEFAULT FALSE,
  refuel_active BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_device_telemetry_latest_device
  ON device_telemetry_latest(device_id);
CREATE INDEX IF NOT EXISTS idx_device_telemetry_latest_recorded
  ON device_telemetry_latest(recorded_at DESC);
