-- TransPoli — hard idempotency for automatic trip settlement side effects.
-- Maintenance generated by settlement and legacy economy-loan installments are
-- identified by the immutable TripId, so recovery/retry cannot duplicate them.

CREATE UNIQUE INDEX IF NOT EXISTS uq_expenses_trip_auto_maintenance
  ON expenses(user_id, trip_id)
  WHERE trip_id IS NOT NULL
    AND type='maintenance'
    AND description LIKE 'Manutencao automatica:%';

CREATE UNIQUE INDEX IF NOT EXISTS uq_economy_trip_loan_payment
  ON economy_ledger(trip_id, entry_type)
  WHERE trip_id IS NOT NULL AND entry_type='loan_payment';
