using System; using System.Data; using System.Net.Http; using System.Text.Json; using System.Threading.Tasks; using System.Windows;
namespace TransPoli;
public partial class DirectorTripHistoryWindow : Window
{
 private const string ApiBaseUrl="https://truckhub.felipe-pessoall2026.workers.dev";
 private readonly HttpClient _http=new(){Timeout=TimeSpan.FromSeconds(10)}; private readonly string _token,_tripId;
 public DirectorTripHistoryWindow(string token,string tripId,string cargo){InitializeComponent();_token=token;_tripId=tripId;TitleText.Text=string.IsNullOrWhiteSpace(cargo)?"Detalhes da viagem":cargo;Loaded+=async(_,_)=>await LoadAsync();}
 private async Task LoadAsync(){try{using var req=new HttpRequestMessage(HttpMethod.Get,ApiBaseUrl+"/director/trips/"+_tripId);req.Headers.TryAddWithoutValidation("Authorization","Bearer "+_token);using var res=await _http.SendAsync(req);var json=await res.Content.ReadAsStringAsync();if(!res.IsSuccessStatusCode){MessageBox.Show(ApiMessage(json,"Não foi possível carregar a viagem."),"TransPoli",MessageBoxButton.OK,MessageBoxImage.Error);return;}using var doc=JsonDocument.Parse(json);var root=doc.RootElement;if(root.TryGetProperty("trip",out var t)){var driver=JsonString(t,"driver","—");var route=$"{JsonString(t,"origin","?")} → {JsonString(t,"destination","?")}";var km=JsonNumber(t,"distance_km");var fuel=JsonNumber(t,"fuel_used_l");var gross=JsonNullable(t,"cargo_value_brl");var status=FormatStatus(JsonString(t,"status","—"));var truck=$"{JsonString(t,"truck_name","")} {JsonString(t,"brand","")} {JsonString(t,"model","")}".Trim();DriverText.Text=driver;RouteText.Text=route;DistanceText.Text=$"{km:N1} km";ResultText.Text=root.TryGetProperty("financial",out var f)&&JsonNullable(f,"resultBrl") is double rr?$"R$ {rr:N2}":"—";SummaryText.Text=$"Status: {status}\nCaminhão: {(string.IsNullOrWhiteSpace(truck)?"—":truck)}\nCarga: {JsonString(t,"cargo","—")}\nCombustível: {fuel:N1} L\nValor bruto: {(gross is double g?$"R$ {g:N2}":"—")}\nInício: {FormatDate(JsonString(t,"started_at","—"))}\nFim: {FormatDate(JsonString(t,"finished_at","—"))}";}if(root.TryGetProperty("expenses",out var e))SetGrid(ExpensesGrid,e,new[]{("Tipo","type"),("Descrição","description"),("Valor","amount"),("Data","created_at")});if(root.TryGetProperty("telemetry",out var tm))SetGrid(TelemetryGrid,tm,new[]{("Data","recorded_at"),("Velocidade","speed_kph"),("RPM","rpm"),("Marcha","gear"),("Combustível","fuel_l"),("Odômetro","odometer_km"),("Autonomia","fuel_range_km")});if(root.TryGetProperty("events",out var ev))SetGrid(EventsGrid,ev,new[]{("Tipo","event_type"),("Data","event_at"),("Dados","payload")});}catch(Exception ex){App.WriteUiCrashLog("DirectorTripHistoryWindow.Load",ex);MessageBox.Show("Não foi possível carregar os detalhes da viagem.","TransPoli",MessageBoxButton.OK,MessageBoxImage.Error);}}
 private static void SetGrid(System.Windows.Controls.DataGrid grid,JsonElement value,(string Header,string Property)[] cols){var table=new DataTable();foreach(var c in cols)table.Columns.Add(c.Header,typeof(string));if(value.ValueKind==JsonValueKind.Array)foreach(var item in value.EnumerateArray()){var row=table.NewRow();for(var i=0;i<cols.Length;i++)row[i]=item.ValueKind==JsonValueKind.Object&&item.TryGetProperty(cols[i].Property,out var p)?FormatValue(cols[i].Property,p):"";table.Rows.Add(row);}grid.ItemsSource=table.DefaultView;}
 private static string FormatValue(string property,JsonElement value){if(value.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)return "";var raw=value.ToString();if(property.EndsWith("_at",StringComparison.Ordinal))return FormatDate(raw);if(property=="amount"&&TryNumber(value,out var money))return $"R$ {money:N2}";if(property is "speed_kph" or "odometer_km" or "fuel_range_km"&&TryNumber(value,out var number))return $"{number:N1}";if(property=="fuel_l"&&TryNumber(value,out var fuel))return $"{fuel:N1} L";if(property=="status")return FormatStatus(raw);return raw;}
 private static string FormatDate(string raw)=>DateTime.TryParse(raw,out var dt)?dt.ToLocalTime().ToString("dd/MM/yyyy HH:mm"):raw;
 private static string FormatStatus(string raw)=>raw.ToLowerInvariant() switch{"active"=>"EM ANDAMENTO","finished"=>"CONCLUÍDA","cancelled"=>"CANCELADA","pending"=>"PENDENTE",_=>raw.ToUpperInvariant()};
 private static string JsonString(JsonElement v,string p,string f)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(p,out var x)&&x.ValueKind!=JsonValueKind.Null?x.GetString()??f:f;
 private static double JsonNumber(JsonElement v,string p)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(p,out var x)&&TryNumber(x,out var n)?n:0;
 private static bool TryNumber(JsonElement v,out double n){if(v.ValueKind==JsonValueKind.Number)return v.TryGetDouble(out n);if(v.ValueKind==JsonValueKind.String)return double.TryParse(v.GetString(),System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out n)||double.TryParse(v.GetString(),out n);n=0;return false;}
 private static double? JsonNullable(JsonElement v,string p)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(p,out var x)&&x.ValueKind!=JsonValueKind.Null&&TryNumber(x,out var n)?n:null;
 private static string ApiMessage(string json,string fallback){try{using var d=JsonDocument.Parse(json);return d.RootElement.TryGetProperty("error",out var p)?p.GetString()??fallback:fallback;}catch{return fallback;}}
 private void Close_Click(object s,RoutedEventArgs e)=>Close();
}