using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
using System.Runtime.CompilerServices;

namespace TransPoli;

public partial class MainWindow
{
    private DispatcherTimer? _v13FixTimer; private bool _v13EngineInitialized; private bool _v13LastEngine; private bool _v13RecoveryBusy; private bool _v13GarageOpening; private static readonly TimeSpan V13Poll=TimeSpan.FromMilliseconds(750);
    internal void StartV13Fixes(){if(_v13FixTimer!=null)return;_v13FixTimer=new DispatcherTimer{Interval=V13Poll};_v13FixTimer.Tick+=async(_,_)=>await V13TickAsync();_v13FixTimer.Start();_=V13TickAsync();}
    private async Task V13TickAsync(){if(_v13RecoveryBusy)return;try{ResizeOperationalModalToTablet();StabilizeOperationsAlert();using var response=await _http.GetAsync(TelemetryUrl);if(!response.IsSuccessStatusCode)return;await using var stream=await response.Content.ReadAsStreamAsync();var data=await JsonSerializer.DeserializeAsync<TelemetrySnapshot>(stream,new JsonSerializerOptions{PropertyNameCaseInsensitive=true});if(data is null||!data.Connected)return;var stopped=Math.Abs(data.SpeedKph)<0.5f;if(!_v13EngineInitialized){_v13EngineInitialized=true;_v13LastEngine=data.EngineEnabled;if(data.EngineEnabled&&!stopped&&!_garageUnauthorized)_truckLocked=false;}else{if(!_v13LastEngine&&data.EngineEnabled&&!_garageUnauthorized)_truckLocked=false;if(_v13LastEngine&&!data.EngineEnabled&&stopped)_truckLocked=true;_v13LastEngine=data.EngineEnabled;}if(_garageUnauthorized)_truckLocked=true;if(!_tripActive&&HasActiveJob(data)&&data.CargoLoaded)await RecoverExistingTripAsync(data);}catch{}finally{ResizeOperationalModalToTablet();StabilizeOperationsAlert();}}
    private async Task RecoverExistingTripAsync(TelemetrySnapshot data){if(_v13RecoveryBusy)return;_v13RecoveryBusy=true;try{var token=SecureTokenStore.Read();if(string.IsNullOrWhiteSpace(token))return;using var request=new HttpRequestMessage(HttpMethod.Get,$"{ApiBaseUrl}/me/trips");request.Headers.TryAddWithoutValidation("Authorization",$"Bearer {token}");request.Headers.TryAddWithoutValidation("Cookie",$"truckhub_session={token}");using var response=await _http.SendAsync(request);if(!response.IsSuccessStatusCode)return;using var doc=JsonDocument.Parse(await response.Content.ReadAsStringAsync());if(!doc.RootElement.TryGetProperty("trips",out var trips)||trips.ValueKind!=JsonValueKind.Array)return;JsonElement? active=null;foreach(var trip in trips.EnumerateArray()){if(!trip.TryGetProperty("status",out var status)||!string.Equals(status.GetString(),"active",StringComparison.OrdinalIgnoreCase))continue;var cargo=trip.TryGetProperty("cargo",out var c)?c.GetString():null;if(!string.IsNullOrWhiteSpace(data.Cargo)&&!string.Equals(cargo,data.Cargo,StringComparison.OrdinalIgnoreCase))continue;active=trip;break;}if(active is null)return;var tripElement=active.Value;var id=tripElement.TryGetProperty("id",out var idElement)?idElement.GetString():null;if(string.IsNullOrWhiteSpace(id))return;_serverTripId=id;_tripActive=true;_tripStartedAtUtc=tripElement.TryGetProperty("started_at",out var started)&&DateTime.TryParse(started.GetString(),CultureInfo.InvariantCulture,DateTimeStyles.AdjustToUniversal,out var parsedStart)?parsedStart.ToUniversalTime():DateTime.UtcNow;try{using var previewRequest=new HttpRequestMessage(HttpMethod.Get,$"{ApiBaseUrl}/me/trips/{id}/economy-preview");previewRequest.Headers.TryAddWithoutValidation("Authorization",$"Bearer {token}");previewRequest.Headers.TryAddWithoutValidation("Cookie",$"truckhub_session={token}");using var previewResponse=await _http.SendAsync(previewRequest);if(previewResponse.IsSuccessStatusCode){using var previewDoc=JsonDocument.Parse(await previewResponse.Content.ReadAsStringAsync());if(previewDoc.RootElement.TryGetProperty("preview",out var preview)&&preview.TryGetProperty("distanceKm",out var distanceElement)){var distance=Math.Max(0,distanceElement.GetSingle());_tripStartOdometer=Math.Max(0,data.OdometerKm-(float)distance);}else _tripStartOdometer=data.OdometerKm;}else _tripStartOdometer=data.OdometerKm;}catch{_tripStartOdometer=data.OdometerKm;}_tripStartFuel=data.FuelLiters;_jobMissingTicks=0;TripStatusText.Text="VIAGEM EM ANDAMENTO • TELEMETRIA RECUPERADA";TripRouteText.Text=BuildRoute(data);TripCargoText.Text=string.IsNullOrWhiteSpace(data.Cargo)?"Carga não informada":$"Carga: {data.Cargo}";TripDistanceText.Text=$"{Math.Max(0,data.OdometerKm-_tripStartOdometer):0.0} km";TripDurationText.Text=FormatDuration(DateTime.UtcNow-_tripStartedAtUtc);TripLiveText.Text=data.GamePaused?"JOGO PAUSADO":"AO VIVO";StatusText.Text="TransPoli • viagem ativa recuperada da telemetria";}catch{}finally{_v13RecoveryBusy=false;}}
    private void StabilizeOperationsAlert(){try{if(_garageUnauthorized){AlertText.Text=string.IsNullOrWhiteSpace(_garageMessage)?"🔒 CAMINHÃO NÃO AUTORIZADO NA GARAGEM":_garageMessage;AlertText.Foreground=FindResource("Yellow") as Brush;return;}if(_truckLocked){AlertText.Text="🔒 CAMINHÃO BLOQUEADO • DESBLOQUEIO NECESSÁRIO";AlertText.Foreground=FindResource("Yellow") as Brush;return;}if(_lastFuelLiters.HasValue)FuelAutoText.Text=$"Abastecimento automático: monitorando • {_lastFuelLiters.Value:0.0} L";AlertText.Text="✓ OPERAÇÃO NORMAL";AlertText.Foreground=FindResource("Green") as Brush;}catch{}}
    private void ResizeOperationalModalToTablet(){try{if(_documentModalLayer?.Child is not FrameworkElement card)return;var width=Math.Max(320,ActualWidth-28);var height=Math.Max(260,ActualHeight-28);card.HorizontalAlignment=HorizontalAlignment.Center;card.VerticalAlignment=VerticalAlignment.Center;card.Width=Math.Min(width,700);card.Height=Math.Min(height,930);card.MaxWidth=700;card.MaxHeight=930;}catch{}}
    internal void ShowFuelPaymentModalV13(){var telemetry=_pendingRefuelTelemetry;var liters=_pendingRefuelLiters;if(telemetry is null||liters<=0){ShowFuelTelemetryUnavailableModalV13();return;}var panel=new StackPanel();panel.Children.Add(ModalPanel(new TextBlock{Text=$"⛽ ABASTECIMENTO DETECTADO\n{liters:0.0} litros adicionados ao tanque. Os litros foram obtidos automaticamente pela telemetria. Informe somente o preço do combustível e o posto. O débito só será lançado depois de confirmar.",FontSize=13,FontWeight=FontWeights.Bold,Foreground=FindResource("Text") as Brush,TextWrapping=TextWrapping.Wrap}));var price=NewV13TextBox("Preço por litro (R$)");var station=NewV13TextBox("Nome do posto");panel.Children.Add(ModalLabel("PREÇO DO COMBUSTÍVEL (R$/L)"));panel.Children.Add(price);panel.Children.Add(ModalLabel("POSTO"));panel.Children.Add(station);panel.Children.Add(ModalLine($"Quantidade abastecida: {liters:0.0} L (telemetria)\nTotal será calculado automaticamente: {liters:0.0} L × preço informado.",12));var save=ModalButton("✓ CONFIRMAR ABASTECIMENTO E DESCONTAR DO BANCO");save.Click+=async(_,e)=>{e.Handled=true;if(!TryMoney(price.Text,out var priceValue)||priceValue<=0||string.IsNullOrWhiteSpace(station.Text)){StatusText.Text="TransPoli • informe apenas o preço do combustível e o posto";return;}await RegisterFuelPaymentV13Async(telemetry,liters,priceValue,station.Text.Trim(),"");};panel.Children.Add(save);var cancel=ModalButton("✕ CANCELAR");cancel.Click+=(_,e)=>{e.Handled=true;_pendingRefuelTelemetry=null;_pendingRefuelLiters=0;CloseOperationalModal();};panel.Children.Add(cancel);ShowModalContent("fuel-v13",BuildModalCard("⛽ ABASTECIMENTO",panel,"Litros capturados automaticamente pela telemetria"));}
    private void ShowFuelTelemetryUnavailableModalV13(){var panel=new StackPanel();panel.Children.Add(ModalPanel(new TextBlock{Text="⛽ ABASTECIMENTO\nNão foi possível obter da telemetria a quantidade abastecida. Para proteger o Banco do Motorista, o TransPoli não permite digitar os litros manualmente. Aguarde a telemetria registrar a operação e tente novamente.",FontSize=13,FontWeight=FontWeights.Bold,Foreground=FindResource("Text") as Brush,TextWrapping=TextWrapping.Wrap}));var close=ModalButton("FECHAR");close.Click+=(_,e)=>{e.Handled=true;CloseOperationalModal();};panel.Children.Add(close);ShowModalContent("fuel-v13",BuildModalCard("⛽ ABASTECIMENTO",panel,"Aguardando dados válidos da telemetria"));}
    private async Task RegisterFuelPaymentV13Async(TelemetrySnapshot data,float liters,decimal price,string station,string city){var token=SecureTokenStore.Read();if(string.IsNullOrWhiteSpace(token)){StatusText.Text="TransPoli • sessão não encontrada";return;}var amount=Math.Round((decimal)liters*price,2);try{var payload=new{liters,pricePerLiter=price,amount,station,city,odometerKm=data.OdometerKm,truckBrand=data.TruckBrand,truckModel=data.TruckModel,licensePlate=data.LicensePlate,tripId=_serverTripId};using var request=new HttpRequestMessage(HttpMethod.Post,$"{ApiBaseUrl}/me/expenses/fuel-payment");request.Headers.TryAddWithoutValidation("Authorization",$"Bearer {token}");request.Headers.TryAddWithoutValidation("Cookie",$"truckhub_session={token}");request.Content=new StringContent(JsonSerializer.Serialize(payload),Encoding.UTF8,"application/json");using var response=await _http.SendAsync(request);var text=await response.Content.ReadAsStringAsync();if(!response.IsSuccessStatusCode){StatusText.Text="TransPoli • "+TryApiError(text,"não foi possível lançar o abastecimento");return;}_refuelings.Add(new RefuelingRecord{Id=Guid.NewGuid().ToString("N"),RecordedAtUtc=DateTime.UtcNow,Station=station,Location=city,Liters=liters,FuelBefore=_fuelBefore,FuelAfter=_fuelAfter,OdometerKm=data.OdometerKm,Truck=$"{data.TruckBrand} {data.TruckModel}".Trim(),LicensePlate=data.LicensePlate??""});SaveOperations();UpdateOpsCounters();_pendingRefuelTelemetry=null;_pendingRefuelLiters=0;StatusText.Text=$"TransPoli • abastecimento confirmado • R$ {amount:0.00} debitado do banco";CloseOperationalModal();}catch{StatusText.Text="TransPoli • erro de comunicação ao registrar o abastecimento";}}
    private static TextBox NewV13TextBox(string placeholder)=>new(){ToolTip=placeholder,FontSize=15,Padding=new Thickness(10),Background=Application.Current.FindResource("Panel2") as Brush,Foreground=Application.Current.FindResource("Text") as Brush,BorderBrush=Application.Current.FindResource("Panel2") as Brush,Margin=new Thickness(0,0,0,2)};
    private static bool TryMoney(string text,out decimal value)=>decimal.TryParse(text.Trim().Replace('.',','),NumberStyles.Number,CultureInfo.GetCultureInfo("pt-BR"),out value)||decimal.TryParse(text.Trim().Replace(',','.'),NumberStyles.Number,CultureInfo.InvariantCulture,out value);
    internal void ShowGarageFromSaveV13(){if(_v13GarageOpening)return;_v13GarageOpening=true;try{var scan=Ets2SaveScanner.Scan();var panel=new StackPanel();panel.Children.Add(ModalLine(scan.Description,12));panel.Children.Add(ModalLabel("CAMINHÕES ENCONTRADOS NO PERFIL / SAVE"));if(scan.Trucks.Count==0)panel.Children.Add(ModalPanel(new TextBlock{Text=scan.ProtectedSaveFound?"O save foi encontrado, mas está protegido/criptografado. Abra o ETS2 e deixe o perfil/save carregado; o TransPoli não modifica o save.":"Nenhum caminhão legível foi encontrado em Documents\\Euro Truck Simulator 2\\profiles/steam_profiles. Se o Steam Cloud estiver sendo usado, carregue o perfil no jogo e tente novamente.",FontSize=13,Foreground=FindResource("Text") as Brush,TextWrapping=TextWrapping.Wrap}));else foreach(var truck in scan.Trucks){var card=new StackPanel();card.Children.Add(new TextBlock{Text=truck.DisplayName,FontSize=16,FontWeight=FontWeights.Bold,Foreground=FindResource("Text") as Brush,TextWrapping=TextWrapping.Wrap});card.Children.Add(ModalValueRow("Placa",string.IsNullOrWhiteSpace(truck.Plate)?"sem placa":truck.Plate));card.Children.Add(ModalValueRow("Quilometragem",truck.OdometerKm>0?$"{truck.OdometerKm:0.0} km":"não informado"));card.Children.Add(ModalValueRow("Combustível",truck.FuelLiters>0?$"{truck.FuelLiters:0.0} L":"não informado"));card.Children.Add(ModalValueRow("Perfil",truck.ProfileName));var bind=ModalButton("🔐 VINCULAR EXCLUSIVAMENTE A MIM");bind.Click+=async(_,e)=>{e.Handled=true;await BindScannedTruckV13Async(truck);};card.Children.Add(bind);panel.Children.Add(ModalPanel(card));}panel.Children.Add(ModalLine("🔒 Ao vincular, o caminhão fica exclusivo deste motorista. Outro motorista com a mesma chave marca|modelo|placa recebe bloqueio de garagem. O save original é somente leitura.",11));ShowModalContent("garage-v13",BuildModalCard("🚛 GARAGEM TRANSPOLI",panel,"Fonte: perfil/save local do ETS2/ATS"));}finally{_v13GarageOpening=false;}}
    private async Task BindScannedTruckV13Async(Ets2TruckInfo truck){var token=SecureTokenStore.Read();if(string.IsNullOrWhiteSpace(token))return;try{var payload=new{brand=truck.Brand,model=truck.Model,plate=truck.Plate,label=truck.DisplayName};using var request=new HttpRequestMessage(HttpMethod.Post,$"{ApiBaseUrl}/me/garage/bind-current");request.Headers.TryAddWithoutValidation("Authorization",$"Bearer {token}");request.Headers.TryAddWithoutValidation("Cookie",$"truckhub_session={token}");request.Content=new StringContent(JsonSerializer.Serialize(payload),Encoding.UTF8,"application/json");using var response=await _http.SendAsync(request);var text=await response.Content.ReadAsStringAsync();if(!response.IsSuccessStatusCode){StatusText.Text="TransPoli • "+TryApiError(text,"não foi possível vincular o caminhão");return;}StatusText.Text=$"TransPoli • {truck.DisplayName} vinculado exclusivamente à sua garagem";_lastGarageCheck=DateTime.MinValue;await CheckGarageAuthorizationAsync();ShowGarageFromSaveV13();}catch{StatusText.Text="TransPoli • falha ao vincular caminhão do save";}}
    private static string TryApiError(string json,string fallback){try{using var doc=JsonDocument.Parse(json);return doc.RootElement.TryGetProperty("error",out var e)?(e.GetString()??fallback):fallback;}catch{return fallback;}}
}
public sealed class Ets2TruckInfo{public string ProfileName{get;init;}="";public string Brand{get;init;}="";public string Model{get;init;}="";public string Plate{get;init;}="";public float OdometerKm{get;init;}public float FuelLiters{get;init;}public string DisplayName=>string.IsNullOrWhiteSpace(Brand)&&string.IsNullOrWhiteSpace(Model)?"Caminhão":$"{Brand} {Model}".Trim();}
public sealed class Ets2SaveScanResult{public List<Ets2TruckInfo> Trucks{get;}=new();public bool ProtectedSaveFound{get;init;}public string Description{get;init;}="";}
public static class Ets2SaveScanner{public static Ets2SaveScanResult Scan(){var result=new Ets2SaveScanResult{Description="Leitura dos perfis/saves locais (somente leitura)."};try{var roots=new[]{Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Euro Truck Simulator 2"),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"American Truck Simulator")};foreach(var root in roots.Distinct(StringComparer.OrdinalIgnoreCase)){if(!Directory.Exists(root))continue;foreach(var folderName in new[]{"profiles","steam_profiles"}){var folder=Path.Combine(root,folderName);if(!Directory.Exists(folder))continue;foreach(var profile in Directory.EnumerateDirectories(folder)){var profileName=Path.GetFileName(profile);foreach(var save in Directory.EnumerateDirectories(profile)){var game=Path.Combine(save,"game.sii");if(!File.Exists(game))continue;try{var text=File.ReadAllText(game,Encoding.UTF8);foreach(Match m in Regex.Matches(text,"(?s)truck:\\s*\\S+\\s*\\{(?<body>.*?)\\}")){var body=m.Groups["body"].Value;var brand=ReadSii(body,"brand");var model=ReadSii(body,"truck_name");if(string.IsNullOrWhiteSpace(model))model=ReadSii(body,"model");var plate=ReadSii(body,"license_plate");var odo=ReadFloat(body,"odometer");var fuel=ReadFloat(body,"fuel_relative");result.Trucks.Add(new Ets2TruckInfo{ProfileName=profileName,Brand=brand,Model=model,Plate=plate,OdometerKm=odo,FuelLiters=fuel});}}catch{result.ProtectedSaveFound=true;}}}}}}}catch{ }return result;}
    private static string ReadSii(string body,string key){var pattern="\\b"+Regex.Escape(key)+"\\s*:\\s*(?:\\\"(?<q>[^\\\"]*)\\\"|(?<v>[^\\s}]+))";var m=Regex.Match(body,pattern,RegexOptions.IgnoreCase);return m.Success?(m.Groups["q"].Success?m.Groups["q"].Value:m.Groups["v"].Value):string.Empty;}
    private static float ReadFloat(string body,string key){var value=ReadSii(body,key);return float.TryParse(value,NumberStyles.Float,CultureInfo.InvariantCulture,out var n)?n:0;}
}
public static class V13ModuleBootstrap{private static bool _registered;internal static void Register(MainWindow window){if(_registered)return;_registered=true;window.AddHandler(Button.ClickEvent,new RoutedEventHandler((s,e)=>{if(e.OriginalSource is not Button b)return;var tag=b.Tag?.ToString()?.Trim().ToLowerInvariant()??string.Empty;var text=b.Content?.ToString()?.Trim().ToUpperInvariant()??string.Empty;if(tag=="feature-garage"||text.Contains("GARAGEM")){e.Handled=true;window.ShowGarageFromSaveV13();}else if(text.Contains("ABASTECIMENTO")||text.Contains("COMBUSTÍVEL")){e.Handled=true;window.ShowFuelPaymentModalV13();}}),true);}}
